name: Build

on:
 workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'true'

env:
#默认软件包
  FEEDS_CONF: feeds.conf.default
#默认内核配置
  KERNEL_CONF: kconfig.seed
#默认内核宏文件名
  KERNEL_IN: kConfig.in

defaults:
  run:
    shell: bash
    working-directory: scripts

jobs:
  verify :
   runs-on: ubuntu-latest
   name: File Verify
   steps:
   - name: Checkout
      uses: actions/checkout@main

   - name: Verify X86
    run: |
     df -hT $PWD
     

