name: Build

on:
 push:
    branches:
      - main
 workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'true'

env:
#默认软件包
  FEEDS_CONF: feeds.conf.default
#默认内核配置
  KERNEL_CONF: kconfig.seed
#默认内核宏文件名
  KERNEL_IN: kConfig.in

defaults:
  run:
    shell: bash
    working-directory: scripts

jobs:
  verify :
   runs-on: ubuntu-latest
   name: File Verify
   steps:
   - name: Checkout
     uses: actions/checkout@main
     
   - name: Start SSH via tmate
     uses: P3TERX/ssh2actions@main
     if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
     env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      
   - name: Verify OpenWrt
     id: isopenwrt
     uses: andstor/file-existence-action@v1
     with:
      files: "openwrt"

   - name: Verify lede
     id: islede
     uses: andstor/file-existence-action@v1
     with:
      files: "lede"

   - name: Verify lienol
     id: islienol
     uses: andstor/file-existence-action@v1
     with:
      files: "lienol"

  OpenWrt :
   runs-on: ubuntu-latest
   name: OpenWrt Config   
   needs: verify
   if: needs.steps.isopenwrt.outputs.files_exists == 'true'
   steps:
     - name: X86 Config
       id: isx86       
       uses: andstor/file-existence-action@v1
       with:
        files: "openwrt/X86,openwrt/X86/feeds.conf.default,openwrt/X86/config.seed"


